sudo: required
services:
  - docker

before_install:
  - docker build -t langstonmenezes/react-test -f ./client/Dockerfile.dev

script:
  - docker run langstonmenezes/react-test npm test 

after_success:
  - docker build -t langstonmenezes/multi-client ./client
  - docker build -t langstonmenezes/multi-nginx ./nginx
  - docker build -t langstonmenezes/multi-server ./server
  - docker build -t langstonmenezes/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push langstonmenezes/multi-client
  - docker push langstonmenezes/multi-nginx
  - docker push langstonmenezes/multi-server
  - docker push langstonmenezes/multi-worker
